# -*- coding: utf-8 -*-
"""Final project AMIT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fi5_ToTnZ8qSqH9drvqTZi-nAg7wi0ex

First: Installing the libraries needed for the project:
"""

!pip install pandas
import pandas as pd
!pip install numpy
import numpy as np
!pip install matplotlib
import matplotlib.pyplot as plt
!pip install seaborn
import seaborn as sns

"""Showing csv files details:"""

df = pd.read_csv('medical_cost_prediction_dataset.csv')
df

# Display the shape of the dataset
df.shape
#Note:The first number are the rows and the second numbers are the columns.

# Display a sample of rows
df.head(10)

# Display the info of the dataset
df.info()

#Showing the types of each column
df.dtypes

df.isnull().sum()

"""Changing all the strings to numbers if possible:"""

df['gender'] = df['gender'].replace({'Male': 0, 'Female': 1})
"""
Note:
We used the binary datatype where:
Male = 0
Female = 1
"""
# Display the unique values and their counts to verify the transformation
display(df['gender'].value_counts())

df['physical_activity_level'] = df['physical_activity_level'].replace({'Low': 0, 'Medium': 1, 'High': 2})
"""
Note:
We used the ordinal datatype where:
Low = 0
Medium = 1
High = 2
"""
# Display the unique values and their counts to verify the transformation
display(df['physical_activity_level'].value_counts())

df['city_type'] = df['city_type'].replace({'Rural': 0, 'Semi-Urban': 1, 'Urban': 2})
"""
Note:
We used the ordinal datatype where:
Rural = 0
Semi-Urban = 1
Urban = 2
"""
# Display the unique values and their counts to verify the transformation
display(df['city_type'].value_counts())

# Fill missing 'insurance_type' values with the mode
mode_insurance_type = df['insurance_type'].mode()[0]
df['insurance_type'].fillna(mode_insurance_type, inplace=True)

# Display the updated value counts to confirm
display(df['insurance_type'].value_counts(dropna=False))

df['insurance_type'] = df['insurance_type'].replace({'Government': 0, 'Private': 1})
"""
Note:
We used the binary datatype where:
Government = 0
Private = 1
"""
# Display the unique values and their counts to verify the transformation
display(df['insurance_type'].value_counts())

df['smoker'] = df['smoker'].replace({'No': 0, 'Yes': 1})
"""
Note:
We used the binary datatype where:
No = 0
Yes = 1
"""
# Display the unique values and their counts to verify the transformation
display(df['smoker'].value_counts())

#Showing the types of each column again to check if there are any more strings
df.dtypes
#Now all the table have numbers

# Now that all relevant categorical columns are numerical, calculate the correlation matrix
df.corr()

"""From the correlation before we concluded that the daily_steps, asthma , and sleep_hours have we coleration with annual_medical_cost so we will drop them"""

df.drop(columns=['daily_steps', 'asthma', 'sleep_hours'], inplace=True)

#Showing all the columns after dropping the unessesary columns
display(df.columns)

